#!/usr/bin/env bash
#Install nginx on your web-01 server
apt-get update
apt-get -y install nginx

service nginx start

echo "Holberton School" > /var/www/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
