#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/page404.html
sed -i '/server_name _;/ a error_page 404 /page404.html;\nlocation = /page404.html {\nroot /var/www/html;\ninternal;\n}' /etc/nginx/sites-available/default

service nginx start