#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
counter=1
while [ $counter -le 10 ]
    do
    echo $counter "Holberton School"
    if [ $counter -eq 9 ]
    then
        echo $counter "Hi"
    fi
    counter=$(( counter+1 ))
    done
