#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
counter=1
while [ $counter -le 10 ]
    do
    if [[ $counter -eq 9 ]]
    then
        echo "Hi"
        ((counter++))
    fi
    echo "Holberton School"
    ((counter++))
    done
